### ISSUE TITLE
+ button is disabled

### ISSUE THREAD

**Issue by winkler1** [danyim/indecks#1]
Hi-
 Not sure if this is finished or not, but the + button is disabled. Known issue?
 Saw that you're adding google auth and firebase - sounds awesome!
Thanks,
Jeff

**Comment by danyim** [comment]
Thanks for reporting this. I noticed this issue too after I published the project to Github Pages. Unfortunately, this is because GH pages doesn't play too well with SPAs with their own URL routers.

A workaround for now is to click on the Indecks logo after the page loads to force it to navigate to the '/' route.

I'll see if I can get this hosted elsewhere for a more permanent fix. Until then, thanks again for checking the app out!

**Comment by danyim** [comment]
Following up on this old issue. There is now a global keyboard shortcut "i" that will open the Add/Import deck. I've also prevented the add button from being disabled on the first load of the app via https://github.com/danyim/indecks/commit/60ef33ec9c61e145d237c58d84ea3ad8a61c9e58
